src/Presentation/SmartStore.Web/Models/Customer/AccountActivationModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class AccountActivationModel : ModelBase
    {
        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/BackInStockSubscriptionModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class BackInStockSubscriptionModel : EntityModelBase
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string SeName { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using FluentValidation.Attributes;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Validators.Customer;

namespace SmartStore.Web.Models.Customer
{
    [Validator(typeof(ChangePasswordValidator))]
    public partial class ChangePasswordModel : ModelBase
    {
        [AllowHtml]
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.OldPassword")]
        public string OldPassword { get; set; }

        [AllowHtml]
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.NewPassword")]
        public string NewPassword { get; set; }

        [AllowHtml]
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.ConfirmNewPassword")]
        public string ConfirmNewPassword { get; set; }

        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressEditModel.cs
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressEditModel : ModelBase
    {
        public CustomerAddressEditModel()
        {
            this.Address = new AddressModel();
        }
        public AddressModel Address { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAvatarModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAvatarModel : ModelBase
    {
        public string AvatarUrl { get; set; }
		public string MaxFileSize { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/CountryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Framework.Controllers;

namespace SmartStore.Web.Controllers
{
    public partial class CountryController : PublicControllerBase
	{
		#region Fields

        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly ICacheManager _cacheManager;

	    #endregion

		#region Constructors

        public CountryController(ICountryService countryService, 
            IStateProvinceService stateProvinceService, 
            ILocalizationService localizationService, 
            IWorkContext workContext,
            ICacheManager cacheManager)
		{
            this._countryService = countryService;
            this._stateProvinceService = stateProvinceService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._cacheManager = cacheManager;
		}

        #endregion

        #region States / provinces

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult GetStatesByCountryId(string countryId, bool addEmptyStateIfRequired)
        {
            //this action method gets called via an ajax request
            if (String.IsNullOrEmpty(countryId))
                throw new ArgumentNullException("countryId");

            string cacheKey = string.Format(ModelCacheEventConsumer.STATEPROVINCES_BY_COUNTRY_MODEL_KEY, countryId, addEmptyStateIfRequired, _workContext.WorkingLanguage.Id);
            var cacheModel = _cacheManager.Get(cacheKey, () =>
            {
                var country = _countryService.GetCountryById(Convert.ToInt32(countryId));
                var states = _stateProvinceService.GetStateProvincesByCountryId(country != null ? country.Id : 0).ToList();
                var result = (from s in states
                              select new { id = s.Id, name = s.GetLocalized(x => x.Name) })
                              .ToList();

                if (addEmptyStateIfRequired && result.Count == 0)
                    result.Insert(0, new { id = 0, name = _localizationService.GetResource("Address.OtherNonUS") });
                return result;

            });

            return Json(cacheModel, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Controllers/DownloadController.cs
using System;
using System.Web;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Media;
using SmartStore.Core.Html;
using SmartStore.Services.Catalog;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Web.Framework.Controllers;

namespace SmartStore.Web.Controllers
{
	public partial class DownloadController : PublicControllerBase
	{
		private readonly IDownloadService _downloadService;
		private readonly IProductService _productService;
		private readonly IOrderService _orderService;
		private readonly IWorkContext _workContext;

		private readonly CustomerSettings _customerSettings;

		public DownloadController(
			IDownloadService downloadService,
			IProductService productService,
			IOrderService orderService,
			IWorkContext workContext,
			CustomerSettings customerSettings)
		{
			this._downloadService = downloadService;
			this._productService = productService;
			this._orderService = orderService;
			this._workContext = workContext;
			this._customerSettings = customerSettings;
		}

		private ActionResult GetFileContentResultFor(Download download, Product product, byte[] data)
		{
			if (data == null || data.LongLength == 0)
				return Content(T("Common.Download.NoDataAvailable"));

			var fileName = (download.Filename.HasValue() ? download.Filename : download.Id.ToString());
			var contentType = (download.ContentType.HasValue() ? download.ContentType : "application/octet-stream");

			return new FileContentResult(data, contentType)
			{
				FileDownloadName = fileName + download.Extension
			};
		}

		private ActionResult GetFileContentResultFor(Download download, Product product)
		{
			return GetFileContentResultFor(download, product, _downloadService.LoadDownloadBinary(download));
		}
        
		public ActionResult Sample(int productId)
        {
            var product = _productService.GetProductById(productId);
            if (product == null)
				return HttpNotFound();

			if (!product.HasSampleDownload)
				return Content(T("Common.Download.HasNoSample"));

			var download = _downloadService.GetDownloadById(product.SampleDownloadId.GetValueOrDefault());
            if (download == null)
                return Content(T("Common.Download.SampleNotAvailable"));

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

			return GetFileContentResultFor(download, product);
        }

		public ActionResult GetDownload(Guid id, bool agree = false)
        {
			if (id == Guid.Empty)
				return HttpNotFound();

			var orderItem = _orderService.GetOrderItemByGuid(id);
            if (orderItem == null)
				return HttpNotFound();

            var order = orderItem.Order;
            var product = orderItem.Product;
            var hasNotification = false;

            if (!_downloadService.IsDownloadAllowed(orderItem))
            {
                hasNotification = true;
                NotifyError(T("Common.Download.NotAllowed"));
            }
            
            if (_customerSettings.DownloadableProductsValidateUser)
            {
                if (_workContext.CurrentCustomer == null)
                    return new HttpUnauthorizedResult();

                if (order.CustomerId != _workContext.CurrentCustomer.Id)
                {
                    hasNotification = true;
                    NotifyError(T("Account.CustomerOrders.NotYourOrder"));
                }
            }

            var download = _downloadService.GetDownloadById(product.DownloadId);
            if (download == null)
            {
                hasNotification = true;
                NotifyError(T("Common.Download.NoDataAvailable"));
            }

			if (product.HasUserAgreement && !agree)
            {
                hasNotification = true;
            }

            if (!product.UnlimitedDownloads && orderItem.DownloadCount >= product.MaxNumberOfDownloads)
            {
                hasNotification = true;
                NotifyError(T("Common.Download.MaxNumberReached", product.MaxNumberOfDownloads));
            }
            
            if (hasNotification)
            {
                return RedirectToAction("UserAgreement", "Customer", new { id = id });
            }
            
            if (download.UseDownloadUrl)
            {
                orderItem.DownloadCount++;
                _orderService.UpdateOrder(order);

                return new RedirectResult(download.DownloadUrl);
            }
            else
            {
				var data = _downloadService.LoadDownloadBinary(download);

				if (data == null || data.LongLength == 0)
                {
                    NotifyError(T("Common.Download.NoDataAvailable"));
                    return RedirectToAction("UserAgreement", "Customer", new { id = id });
                }
                
                orderItem.DownloadCount++;
                _orderService.UpdateOrder(order);

				return GetFileContentResultFor(download, product, data);
            }
        }

		public ActionResult GetLicense(Guid id)
        {
			if (id == Guid.Empty)
				return HttpNotFound();
			
			var orderItem = _orderService.GetOrderItemByGuid(id);
            if (orderItem == null)
				return HttpNotFound();

            var order = orderItem.Order;
            var product = orderItem.Product;

            if (!_downloadService.IsLicenseDownloadAllowed(orderItem))
                return Content(T("Common.Download.NotAllowed"));

            if (_customerSettings.DownloadableProductsValidateUser)
            {
                if (_workContext.CurrentCustomer == null)
                    return new HttpUnauthorizedResult();

                if (order.CustomerId != _workContext.CurrentCustomer.Id)
                    return Content(T("Account.CustomerOrders.NotYourOrder"));
            }

            var download = _downloadService.GetDownloadById(orderItem.LicenseDownloadId.HasValue ? orderItem.LicenseDownloadId.Value : 0);
            if (download == null)
                return Content(T("Common.Download.NotAvailable"));
            
            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

			return GetFileContentResultFor(download, product);
		}

        public ActionResult GetFileUpload(Guid downloadId)
        {
            var download = _downloadService.GetDownloadByGuid(downloadId);
            if (download == null)
                return Content(T("Common.Download.NotAvailable"));

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

			return GetFileContentResultFor(download, null);
		}

		public ActionResult GetUserAgreement(int productId, bool? asPlainText)
		{
			var product = _productService.GetProductById(productId);
			if (product == null)
				return Content(T("Products.NotFound", productId));

			if (!product.IsDownload || !product.HasUserAgreement || product.UserAgreementText.IsEmpty())
				return Content(T("DownloadableProducts.HasNoUserAgreement"));

			if (asPlainText ?? false)
			{
				var agreement = HtmlUtils.ConvertHtmlToPlainText(product.UserAgreementText);
				agreement = HtmlUtils.StripTags(HttpUtility.HtmlDecode(agreement));

				return Content(agreement);
			}

			return Content(product.UserAgreementText);
		}
	}
}

src/Presentation/SmartStore.Web/Controllers/TopicController.cs
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Services.Localization;
using SmartStore.Services.Topics;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Topics;
using SmartStore.Web.Framework.Controllers;

namespace SmartStore.Web.Controllers
{
    public partial class TopicController : PublicControllerBase
    {
        #region Fields

        private readonly ITopicService _topicService;
        private readonly IWorkContext _workContext;
		private readonly IStoreContext _storeContext;
        private readonly ILocalizationService _localizationService;
        private readonly ICacheManager _cacheManager;

        #endregion

        #region Constructors

        public TopicController(ITopicService topicService,
            ILocalizationService localizationService,
            IWorkContext workContext,
			IStoreContext storeContext,
			ICacheManager cacheManager)
        {
            this._topicService = topicService;
            this._workContext = workContext;
			this._storeContext = storeContext;
            this._localizationService = localizationService;
            this._cacheManager = cacheManager;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected TopicModel PrepareTopicModel(string systemName)
        {
			//load by store
			var topic = _topicService.GetTopicBySystemName(systemName, _storeContext.CurrentStore.Id);
            if (topic == null)
                return null;

            var titleTag = "h3";
            if(topic.TitleTag != null)
                titleTag = topic.TitleTag;
            else if (!topic.RenderAsWidget) 
                 titleTag = "h1";

            var model = new TopicModel()
            {
                Id = topic.Id,
                SystemName = topic.SystemName,
                IsPasswordProtected = topic.IsPasswordProtected,
                Title = topic.IsPasswordProtected ? "" : topic.GetLocalized(x => x.Title),
                Body = topic.IsPasswordProtected ? "" : topic.GetLocalized(x => x.Body),
                MetaKeywords = topic.GetLocalized(x => x.MetaKeywords),
                MetaDescription = topic.GetLocalized(x => x.MetaDescription),
                MetaTitle = topic.GetLocalized(x => x.MetaTitle),
                TitleTag = titleTag,
				RenderAsWidget = topic.RenderAsWidget
			};

			if (!topic.RenderAsWidget)
			{
				Services.DisplayControl.Announce(topic);
			}

            return model;
        }

        #endregion

        #region Methods

        public ActionResult TopicDetails(string systemName)
        {
			var cacheKey = string.Format(ModelCacheEventConsumer.TOPIC_MODEL_KEY, systemName, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cacheModel = _cacheManager.Get(cacheKey, () => PrepareTopicModel(systemName));

			if (cacheModel == null || (cacheModel.RenderAsWidget))
				return HttpNotFound();

            return View("TopicDetails", cacheModel);
        }

        public ActionResult TopicDetailsPopup(string systemName)
        {
			var cacheKey = string.Format(ModelCacheEventConsumer.TOPIC_MODEL_KEY, systemName, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cacheModel = _cacheManager.Get(cacheKey, () => PrepareTopicModel(systemName));

            if (cacheModel == null)
				return HttpNotFound();

            ViewBag.IsPopup = true;
            return View("TopicDetails", cacheModel);
        }

        [ChildActionOnly]
        public ActionResult TopicBlock(string systemName, bool bodyOnly = false, bool isLead = false)
        {
			var cacheKey = string.Format(ModelCacheEventConsumer.TOPIC_MODEL_KEY, systemName, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cacheModel = _cacheManager.Get(cacheKey, () => PrepareTopicModel(systemName));

            if (cacheModel == null)
                return Content("");

            ViewBag.BodyOnly = bodyOnly;
			ViewBag.IsLead = isLead;

			return PartialView(cacheModel);
        }

        [ChildActionOnly]
        public ActionResult TopicWidget(TopicWidgetModel model)
        {
            return PartialView(model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Authenticate(int id, string password)
        {
            var authResult = false;
            var title = string.Empty;
            var body = string.Empty;
            var error = string.Empty;

            var topic = _topicService.GetTopicById(id);

            if (topic != null)
            {
                if (topic.Password != null && topic.Password.Equals(password))
                {
                    authResult = true;
                    title = topic.GetLocalized(x => x.Title);
                    body = topic.GetLocalized(x => x.Body);
                }
                else
                {
                    error = _localizationService.GetResource("Topic.WrongPassword");
                }
            }
            return Json(new { Authenticated = authResult, Title = title, Body = body, Error = error });
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Views/Customer/AccountActivation.cshtml
@model AccountActivationModel
@using SmartStore.Web.Models.Customer;
@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.AccountActivation").Text);
}

<div class="page account-activation-page">
    <div class="page-title">
        <h1>@T("Account.AccountActivation")</h1>
    </div>
    <div class="page-body">
        <strong>@Model.Result</strong>
    </div>
</div>

src/Presentation/SmartStore.Web/Views/Customer/AddressEdit.cshtml
@model CustomerAddressEditModel

@using SmartStore.Web.Models.Customer;

@{
	Html.AddTitleParts(T("PageTitle.Account").Text);

	Layout = "_MyAccount";
	ViewBag.PageClassToken = "addresses";
	ViewBag.PageTitle = T("Account.CustomerAddresses.Edit").Text;
}

@using (Html.BeginForm())
{
	var dataDictAddress = new ViewDataDictionary();
	dataDictAddress["breakpoint"] = "lg";
	// Merge ModelState (required for validation)
	dataDictAddress.ModelState.Merge(ViewData.ModelState);
	dataDictAddress.TemplateInfo.HtmlFieldPrefix = "Address";
	Html.RenderPartial("_CreateOrUpdateAddress", Model.Address, dataDictAddress);

	<div class="form-group row">
		<div class="col">
			<button type="submit" class="btn btn-primary btn-lg save-address-button">
				<i class="fa fa-check"></i>
				<span>@T("Common.Save")</span>
			</button>
		</div>
	</div>
}

src/Presentation/SmartStore.Web/Views/Customer/ChangePassword.cshtml
@model ChangePasswordModel

@using SmartStore.Web.Models.Customer;

@{
	Html.AddTitleParts(T("PageTitle.Account").Text);

	Layout = "_MyAccount";
	ViewBag.PageClassToken = "changepassword";
	ViewBag.PageTitle = T("Account.ChangePassword").Text;
}

@using (Html.BeginForm("ChangePassword", "Customer", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

	if (!ViewData.ModelState.IsValid)
	{
        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
    }

    if (!String.IsNullOrEmpty(Model.Result))
    {
        <div class="alert alert-info">
            @Model.Result
        </div>
    }

    <div class="form-group row">
        @Html.LabelFor(model => model.OldPassword, new { @class = "col-lg-4 col-form-label required" })
        <div class="col-lg-8">
            @Html.PasswordFor(model => model.OldPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OldPassword)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.NewPassword, new { @class = "col-lg-4 col-form-label required" })
        <div class="col-lg-8">
            @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NewPassword)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.ConfirmNewPassword, new { @class = "col-lg-4 col-form-label required" })
        <div class="col-lg-8">
            @Html.PasswordFor(model => model.ConfirmNewPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ConfirmNewPassword)
        </div>
    </div>

    <div class="form-group row">
        <div class="col">
            <button type="submit" class="btn btn-lg btn-primary">
                <i class="fa fa-check"></i>
                <span>@T("Account.ChangePassword.Button")</span>
            </button>
        </div>
    </div>
}

src/Presentation/SmartStore.Web/Views/Customer/DownloadableProducts.cshtml
@model CustomerDownloadableProductsModel

@using SmartStore.Web.Models.Customer;

@{
	Html.AddTitleParts(T("PageTitle.Account").Text);

	Layout = "_MyAccount";
	ViewBag.PageClassToken = "downloads";
	ViewBag.PageTitle = T("Account.DownloadableProducts").Text;
}

@if (Model.Items.Count == 0)
{
	<div class="alert alert-warning">
		@T("DownloadableProducts.NoItems")
	</div>
	return;
}

<div class="card-deck card-cols-sm-1 esd-list">
	@foreach (var item in Model.Items)
	{
		<div class="card card-shadow esd-item">
			<div class="card-block">
				<h4 class="card-title mb-4">@item.ProductName.Truncate(50, "...")</h4>
				<dl class="row mb-0">
					<dt class="col-sm-3 font-weight-400 text-muted">@T("Order.Order#")</dt>
					<dd class="col-sm-9"><a href="@Url.Action("Details", "Order", new { id = item.OrderId })" rel="nofollow">@item.OrderId</a></dd>
					<dt class="col-sm-3 font-weight-400 text-muted">@T("Common.CreatedOn")</dt>
					<dd class="col-sm-9">@item.CreatedOn.ToString("d")</dd>
					<dt class="col-sm-3 font-weight-400 text-muted">@T("DownloadableProducts.Fields.Product")</dt>
					<dd class="col-sm-9">
						<a href="@item.ProductUrl" title="@T("Products.Details")">@item.ProductName</a>
						@if (item.ProductAttributes.HasValue())
						{
							<div>
								@Html.Raw(item.ProductAttributes)
							</div>
						}
					</dd>
				</dl>
			</div>

			@if (item.DownloadId > 0 || item.LicenseId > 0)
			{
				<div class="card-footer d-flex p-0">
					@if (item.DownloadId > 0)
					{
						<a class="btn btn-secondary btn-flat rounded-0" href="@Url.Action("GetDownload", "Download", new { id = item.OrderItemGuid })" rel="nofollow">
							<i class="fa fa-download"></i>
							<span>@T("DownloadableProducts.Fields.Download")</span>
						</a>
					}
					else
					{
						<a class="btn btn-secondary btn-flat rounded-0 disabled" href="javascript:void(0)" rel="nofollow">
                            <span>@T("DownloadableProducts.Fields.Download.NA")</span>
						</a>
					}

					@if (item.LicenseId > 0)
					{
						<a class="btn btn-secondary btn-flat rounded-0" href="@Url.Action("GetLicense", "Download", new { id = item.OrderItemGuid })" rel="nofollow">
							<span>@T("DownloadableProducts.Fields.DownloadLicense")</span>
						</a>
					}
				</div>
			}
		</div>
	}
</div>

src/Presentation/SmartStore.Web/Views/Customer/Login.cshtml
@model LoginModel

@using SmartStore.Web.Models.Customer;
@using SmartStore.Core;
@using SmartStore.Core.Infrastructure;

@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.Login").Text);

    var registerUrl = Url.RouteUrl("Register");
    if (!String.IsNullOrEmpty(this.Context.Request.QueryString["returnUrl"]))
    {
        var webHelper = EngineContext.Current.Resolve<IWebHelper>();
        registerUrl = webHelper.ModifyQueryString(registerUrl, "returnurl=" + HttpUtility.UrlEncode(this.Context.Request.QueryString["returnUrl"]), null);
    }
}

<div class="page login-page">
	<div class="page-title">
		<h1>@T("Account.Login.Welcome")</h1>
	</div>

	<div class="row mt-4">
		<div class="col-12 col-md-7 col-lg-6 col-xl-5 order-md-last">
			<div class="card card-shadow p-5 mb-5 mb-md-0 login-box">
				<h3 class="h4 mb-0">
					@T("Account.Login.ReturningCustomer")
				</h3>
				<hr />
				@if (!ViewData.ModelState.IsValid)
				{
					@Html.ValidationSummary(true, T("Account.Login.Unsuccessful").Text, new { @class = "alert alert-danger" })
				}

				<!-- SignIn Form -->
				<form action="@ViewContext.HttpContext.Request.RawUrl" method="post">
					@if (Model.UsernamesEnabled)
					{
						<div class="form-group">
							<div class="input-group input-group-lg has-icon">
								@Html.TextBoxFor(m => m.Username, new { @class = "username form-control", placeholder = Html.DisplayNameFor(m => m.Username) })
								<span class="input-group-icon text-muted">
									<i class="icm icm-user"></i>
								</span>
							</div>
							@Html.ValidationMessageFor(m => m.Username)
						</div>
					}
					else
					{
						<div class="form-group">
							<div class="input-group input-group-lg has-icon">
								@Html.TextBoxFor(m => m.Email, new { @class = "email form-control", type = "email", placeholder = Html.DisplayNameFor(m => m.Email) })
								<span class="input-group-icon text-muted">
									<i class="icm icm-envelope-open"></i>
								</span>
							</div>
							@Html.ValidationMessageFor(m => m.Email)
						</div>
					}

					<div class="form-group">
						<div class="input-group input-group-lg has-icon">
							<input type="password" class="password form-control" autocomplete="off"
								   placeholder="@Html.DisplayNameFor(m => m.Password)"
								   id="@Html.FieldIdFor(m => m.Password)"
								   name="@Html.FieldNameFor(m => m.Password)"
								   value="@(Model.Password.HasValue() ? Model.Password : null)" />
							<span class="input-group-icon text-muted">
								<i class="icm icm-shield"></i>
							</span>
						</div>
						@Html.ValidationMessageFor(m => m.Password)
					</div>

					<div class="form-group d-flex justify-content-between">
						<label class="form-check-label">
							@Html.CheckBoxFor(m => m.RememberMe, new { @class = "form-check-input" })
							<span>@T("Account.Login.Fields.RememberMe")</span>
						</label>
						<div class="forgot-password">
							@Html.ActionLink(T("Account.Login.ForgotPassword").Text, "PasswordRecovery", "Customer")
						</div>
					</div>

					@if (Model.DisplayCaptcha)
					{
						<div class="form-group captcha-box">
							@Html.Raw(Html.GenerateCaptcha())
						</div>
					}

					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-lg btn-block btn-login">
							@T("Account.Login.LoginButton")
						</button>
					</div>

					@{ Html.RenderAction("ExternalMethods", "ExternalAuthentication"); }
				</form>
			</div>
		</div>
		<div class="col-12 col-md-5 col-lg-6 col-xl-7 order-md-first">
			<div class="page-info">
				@{
					Html.RenderPartial("_ExternalAuthentication.AssociateMessage");
					Html.RenderAction("TopicBlock", "Topic", new { systemName = "LoginRegistrationInfo", bodyOnly = true, isLead = true });
				}
			</div>

			<div class="register-block">
				@if (Model.CheckoutAsGuest)
				{
					Html.RenderAction("TopicBlock", "Topic", new { systemName = "CheckoutAsGuestOrRegister", bodyOnly = true });
					<div class="row sm-gutters">
						<div class="col-sm-6 col-md-12 col-lg-6 pb-2 pb-lg-0">
							<a class="btn btn-warning btn-lg btn-block register-button" href="@registerUrl">
								@T("Account.Register.Button")
							</a>
						</div>
						<div class="col-sm-6 col-md-12 col-lg-6">
							<a class="btn btn-secondary btn-lg btn-block checkout-as-guest-button" href="@Url.RouteUrl("Checkout")">
								<span>@T("Account.Login.CheckoutAsGuest")</span>
								<i class="fa fa-angle-right"></i>
							</a>
						</div>
					</div>
				}
				else
				{
					<div class="row">
						<div class="col-12 col-lg-auto">
							<a class="btn btn-warning btn-lg btn-block register-button" href="@registerUrl">
								@T("Account.Register.Button")
							</a>
						</div>
					</div>
				}
			</div>
		</div>
	</div>
</div>