src/Presentation/SmartStore.Web/Models/Customer/AccountActivationModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class AccountActivationModel : ModelBase
    {
        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/BackInStockSubscriptionModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class BackInStockSubscriptionModel : EntityModelBase
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string SeName { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using FluentValidation.Attributes;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Validators.Customer;

namespace SmartStore.Web.Models.Customer
{
    [Validator(typeof(ChangePasswordValidator))]
    public partial class ChangePasswordModel : ModelBase
    {
        [AllowHtml]
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.OldPassword")]
        public string OldPassword { get; set; }

        [AllowHtml]
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.NewPassword")]
        public string NewPassword { get; set; }

        [AllowHtml]
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.ConfirmNewPassword")]
        public string ConfirmNewPassword { get; set; }

        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressEditModel.cs
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressEditModel : ModelBase
    {
        public CustomerAddressEditModel()
        {
            this.Address = new AddressModel();
        }
        public AddressModel Address { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressListModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressListModel : ModelBase
    {
        public CustomerAddressListModel()
        {
            Addresses = new List<AddressModel>();
        }

        public IList<AddressModel> Addresses { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAvatarModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAvatarModel : ModelBase
    {
        public string AvatarUrl { get; set; }
		public string MaxFileSize { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerBackInStockSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerBackInStockSubscriptionsModel : PagedListBase
    {
        public CustomerBackInStockSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.Subscriptions = new List<BackInStockSubscriptionModel>();
        }

        public IList<BackInStockSubscriptionModel> Subscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerDownloadableProductsModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerDownloadableProductsModel : ModelBase
    {
        public CustomerDownloadableProductsModel()
        {
            Items = new List<DownloadableProductsModel>();
        }

        public IList<DownloadableProductsModel> Items { get; set; }

        #region Nested classes

        public partial class DownloadableProductsModel : ModelBase
        {
            public Guid OrderItemGuid { get; set; }

            public int OrderId { get; set; }

            public int ProductId { get; set; }
            public string ProductName { get; set; }
            public string ProductSeName { get; set; }
			public string ProductUrl { get; set; }
            public string ProductAttributes { get; set; }

            public int DownloadId { get; set; }
            public int LicenseId { get; set; }

            public DateTime CreatedOn { get; set; }
        }

        #endregion
    }

    public partial class UserAgreementModel : ModelBase
    {
        public Guid OrderItemGuid { get; set; }
        public string UserAgreementText { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerForumSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerForumSubscriptionsModel : PagedListBase
    {
        public CustomerForumSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.ForumSubscriptions = new List<ForumSubscriptionModel>();
        }

        public IList<ForumSubscriptionModel> ForumSubscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerInfoModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using FluentValidation.Attributes;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Validators.Customer;

namespace SmartStore.Web.Models.Customer
{
	[Validator(typeof(CustomerInfoValidator))]
    public partial class CustomerInfoModel : ModelBase
    {
        public CustomerInfoModel()
        {
            this.AvailableTimeZones = new List<SelectListItem>();
            this.AvailableCountries = new List<SelectListItem>();
            this.AvailableStates = new List<SelectListItem>();
            this.AssociatedExternalAuthRecords = new List<AssociatedExternalAuthModel>();
        }

        [SmartResourceDisplayName("Account.Fields.Email")]
        [AllowHtml]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }

        [SmartResourceDisplayName("Account.Fields.CustomerNumber")]
        [AllowHtml]
        public string CustomerNumber { get; set; }
        public bool CustomerNumberEnabled { get; set; }
        public bool DisplayCustomerNumber { get; set; }

        public bool CheckUsernameAvailabilityEnabled { get; set; }
        public bool AllowUsersToChangeUsernames { get; set; }
        public bool UsernamesEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Username")]
        [AllowHtml]
        public string Username { get; set; }

        //form fields & properties
        public bool GenderEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Gender")]
        public string Gender { get; set; }

        public bool TitleEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Title")]
        public string Title { get; set; }
        
        [SmartResourceDisplayName("Account.Fields.FirstName")]
        [AllowHtml]
        public string FirstName { get; set; }
        [SmartResourceDisplayName("Account.Fields.LastName")]
        [AllowHtml]
        public string LastName { get; set; }


        public bool DateOfBirthEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.DateOfBirth")]
        public int? DateOfBirthDay { get; set; }
        [SmartResourceDisplayName("Account.Fields.DateOfBirth")]
        public int? DateOfBirthMonth { get; set; }
        [SmartResourceDisplayName("Account.Fields.DateOfBirth")]
        public int? DateOfBirthYear { get; set; }

        public bool CompanyEnabled { get; set; }
        public bool CompanyRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.Company")]
        [AllowHtml]
        public string Company { get; set; }

        public bool StreetAddressEnabled { get; set; }
        public bool StreetAddressRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.StreetAddress")]
        [AllowHtml]
        public string StreetAddress { get; set; }

        public bool StreetAddress2Enabled { get; set; }
        public bool StreetAddress2Required { get; set; }
        [SmartResourceDisplayName("Account.Fields.StreetAddress2")]
        [AllowHtml]
        public string StreetAddress2 { get; set; }

        public bool ZipPostalCodeEnabled { get; set; }
        public bool ZipPostalCodeRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.ZipPostalCode")]
        [AllowHtml]
        public string ZipPostalCode { get; set; }

        public bool CityEnabled { get; set; }
        public bool CityRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.City")]
        [AllowHtml]
        public string City { get; set; }

        public bool CountryEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Country")]
        public int CountryId { get; set; }
        public IList<SelectListItem> AvailableCountries { get; set; }

        public bool StateProvinceEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.StateProvince")]
        public int StateProvinceId { get; set; }
        public IList<SelectListItem> AvailableStates { get; set; }

        public bool PhoneEnabled { get; set; }
        public bool PhoneRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.Phone")]
        [AllowHtml]
		[DataType(DataType.PhoneNumber)]
		public string Phone { get; set; }

        public bool FaxEnabled { get; set; }
        public bool FaxRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.Fax")]
        [AllowHtml]
		[DataType(DataType.PhoneNumber)]
		public string Fax { get; set; }

        public bool NewsletterEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Newsletter")]
        public bool Newsletter { get; set; }

        //preferences
        public bool SignatureEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Signature")]
        [AllowHtml]
        public string Signature { get; set; }

        //time zone
        [SmartResourceDisplayName("Account.Fields.TimeZone")]
        public string TimeZoneId { get; set; }
        public bool AllowCustomersToSetTimeZone { get; set; }
        public IList<SelectListItem> AvailableTimeZones { get; set; }

        //EU VAT
        [SmartResourceDisplayName("Account.Fields.VatNumber")]
        [AllowHtml]
        public string VatNumber { get; set; }
        public string VatNumberStatusNote { get; set; }
        public bool DisplayVatNumber { get; set; }

        //external authentication
        [SmartResourceDisplayName("Account.AssociatedExternalAuth")]
        public IList<AssociatedExternalAuthModel> AssociatedExternalAuthRecords { get; set; }

        #region Nested classes

        public partial class AssociatedExternalAuthModel : EntityModelBase
        {
            public string Email { get; set; }
            public string ExternalIdentifier { get; set; }
            public string AuthMethodName { get; set; }
        }
        
        #endregion
    }
}

src/Presentation/SmartStore.Web/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Polls;
using SmartStore.Services.Customers;
using SmartStore.Services.Polls;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Polls;

namespace SmartStore.Web.Controllers
{
	public partial class PollController : PublicControllerBase
    {
        #region Fields

        private readonly IWorkContext _workContext;
        private readonly IPollService _pollService;
        private readonly IWebHelper _webHelper;
        private readonly ICacheManager _cacheManager;
		private readonly IStoreContext _storeContext;

        #endregion

        #region Constructors

        public PollController(
            IWorkContext workContext,
			IPollService pollService,
            IWebHelper webHelper,
			ICacheManager cacheManager,
			IStoreContext storeContext)
        {
            this._workContext = workContext;
            this._pollService = pollService;
            this._webHelper = webHelper;
            this._cacheManager = cacheManager;
			this._storeContext = storeContext;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected PollModel PreparePollModel(Poll poll, bool setAlreadyVotedProperty)
        {
            var model = new PollModel
            {
                Id = poll.Id,
                AlreadyVoted = setAlreadyVotedProperty && _pollService.AlreadyVoted(poll.Id, _workContext.CurrentCustomer.Id),
                Name = poll.Name
            };

            var answers = poll.PollAnswers.OrderBy(x => x.DisplayOrder);

			foreach (var answer in answers)
			{
				model.TotalVotes += answer.NumberOfVotes;
			}

            foreach (var pa in answers)
            {
                model.Answers.Add(new PollAnswerModel
                {
                    Id = pa.Id,
                    Name = pa.Name,
                    NumberOfVotes = pa.NumberOfVotes,
                    PercentOfTotalVotes = model.TotalVotes > 0 ? ((Convert.ToDouble(pa.NumberOfVotes) / Convert.ToDouble(model.TotalVotes)) * Convert.ToDouble(100)) : 0,
                });
            }

            return model;
        }

        #endregion

        #region Methods

        [ChildActionOnly]
        public ActionResult PollBlock(string systemKeyword)
        {
            if (String.IsNullOrWhiteSpace(systemKeyword))
                return Content("");

            var cacheKey = string.Format(ModelCacheEventConsumer.POLL_BY_SYSTEMNAME_MODEL_KEY, systemKeyword, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cachedModel = _cacheManager.Get(cacheKey, () =>
            {
                var poll = _pollService.GetPollBySystemKeyword(systemKeyword, _workContext.WorkingLanguage.Id);

                if (poll == null)
					return new PollModel { Id = 0 };	//we do not cache nulls. that's why let's return an empty record (ID = 0)

                return PreparePollModel(poll, false);
            });

            if (cachedModel == null || cachedModel.Id == 0)
                return Content("");

            //"AlreadyVoted" property of "PollModel" object depends on the current customer. Let's update it.
            //But first we need to clone the cached model (the updated one should not be cached)
            var model = (PollModel)cachedModel.Clone();
            model.AlreadyVoted = _pollService.AlreadyVoted(model.Id, _workContext.CurrentCustomer.Id);
            model.SystemKeyword = systemKeyword;

            return PartialView(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Vote(int pollAnswerId)
        {
            var pollAnswer = _pollService.GetPollAnswerById(pollAnswerId);

			if (pollAnswer == null)
			{
				return Json(new	{ error = T("Polls.AnswerNotFound", pollAnswerId).Text });
			}

            var poll = pollAnswer.Poll;

			if (!poll.Published)
			{
				return Json(new	{ error = T("Polls.NotAvailable").Text });
			}

			if (_workContext.CurrentCustomer.IsGuest() && !poll.AllowGuestsToVote)
			{
				return Json(new	{ error = T("Polls.OnlyRegisteredUsersVote").Text });
			}

            bool alreadyVoted = _pollService.AlreadyVoted(poll.Id, _workContext.CurrentCustomer.Id);
            if (!alreadyVoted)
            {
                //vote
                pollAnswer.PollVotingRecords.Add(new PollVotingRecord
                {
                    PollAnswerId = pollAnswer.Id,
                    CustomerId = _workContext.CurrentCustomer.Id,
                    IpAddress = _webHelper.GetCurrentIpAddress(),
                    IsApproved = true
                });

                //update totals
                pollAnswer.NumberOfVotes = pollAnswer.PollVotingRecords.Count;

                _pollService.UpdatePoll(poll);
            }

            return Json(new
            {
                html = this.RenderPartialViewToString("_Poll", PreparePollModel(poll, true)),
            });
        }
        
        [ChildActionOnly]
        public ActionResult HomePagePolls()
        {
            var cacheKey = string.Format(ModelCacheEventConsumer.HOMEPAGE_POLLS_MODEL_KEY, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cachedModel = _cacheManager.Get(cacheKey, () =>
            {
                return _pollService.GetPolls(_workContext.WorkingLanguage.Id, true, 0, int.MaxValue)
                    .Select(x => PreparePollModel(x, false))
                    .ToList();
            });

            //"AlreadyVoted" property of "PollModel" object depends on the current customer. Let's update it.
            //But first we need to clone the cached model (the updated one should not be cached)
            var model = new List<PollModel>();

            foreach (var p in cachedModel)
            {
                var pollModel = (PollModel)p.Clone();
                pollModel.AlreadyVoted = _pollService.AlreadyVoted(pollModel.Id, _workContext.CurrentCustomer.Id);
                pollModel.SystemKeyword = "Homepage";
                model.Add(pollModel);
            }

			if (model.Count == 0)
				return Content("");

            return PartialView(model);
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Views/Customer/Partials/MyAccountMenu.cshtml
@model MyAccountMenuModel     
	      
@using SmartStore.Web.Models.Customer;

@{ 
	var selItem = Model.SelectedItemToken != null ? Model.SelectedItemToken.ToLowerInvariant() : "";
}

@{ Html.RenderWidget("myaccount_menu_before"); }

<div class="card myaccount-menu">
    <h5 class="card-header" style="border-bottom: none">
        @T("Account.Navigation")
    </h5>
    <div class="list-group list-group-flush has-icons">  
        @{ Html.RenderWidget("myaccount_menu_firstitem_before"); }

        @if(!Model.HideInfo)
        {
            <a href="@Url.Action("Info", "Customer")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "info" ? " active" : "")">
                <i class="fa fa-fw fa-user-o list-group-item-icon"></i>
				<span>@T("Account.CustomerInfo")</span>
            </a>
        }
        @if (!Model.HideAddresses)
        {
            <a href="@Url.Action("Addresses", "Customer")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "addresses" ? " active" : "")">
				<i class="fa fa-fw fa-address-book-o list-group-item-icon"></i>
				<span>@T("Account.CustomerAddresses")</span>
            </a>
		}
        @if (!Model.HideOrders)
		{ 
            <a href="@Url.Action("Orders", "Customer")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "orders" ? " active" : "")">
				<i class="fa fa-fw fa-file-text list-group-item-icon"></i>
				<span>@T("Account.CustomerOrders")</span>
            </a>
		}
        @if (!Model.HideReturnRequests)
		{ 
            <a href="@Url.Action("ReturnRequests", "Customer")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "returnrequests" ? " active" : "")">
				<i class="fa fa-fw fa-truck list-group-item-icon"></i>
				<span>@T("Account.CustomerReturnRequests")</span>
            </a>
		}
        @if (!Model.HideDownloadableProducts)
		{ 
            <a href="@Url.Action("DownloadableProducts", "Customer")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "downloads" ? " active" : "")">
				<i class="fa fa-fw fa-download list-group-item-icon"></i>
				<span>@T("Account.DownloadableProducts")</span>
            </a>
        }
        @if (!Model.HideBackInStockSubscriptions)
        { 
            <a href="@Url.Action("BackInStockSubscriptions")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "backinstock" ? " active" : "")">
				<i class="fa fa-fw fa-bullhorn list-group-item-icon"></i>
				<span>@T("Account.BackInStockSubscriptions")</span>
            </a>
        }
        @if (!Model.HideRewardPoints)
        { 
            <a href="@Url.Action("RewardPoints")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "rewardpoints" ? " active" : "")">
				<i class="fa fa-fw fa-certificate list-group-item-icon"></i>
				<span>@T("Account.RewardPoints")</span>
            </a>
        }
        @if (!Model.HideChangePassword)
        { 
            <a href="@Url.Action("ChangePassword")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "changepassword" ? " active" : "")">
				<i class="fa fa-fw fa-unlock-alt list-group-item-icon"></i>
				<span>@T("Account.ChangePassword")</span>
            </a>
        }
        @if (!Model.HideAvatar)
        { 
            <a href="@Url.Action("Avatar")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "avatar" ? " active" : "")">
				<i class="fa fa-fw fa-user-circle list-group-item-icon"></i>
				<span>@T("Account.Avatar")</span>
            </a>
        }
        @if (!Model.HideForumSubscriptions)
        { 
            <a href="@Url.Action("ForumSubscriptions")" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "forumsubscriptions" ? " active" : "")">
				<i class="fa fa-fw fa-bell list-group-item-icon"></i>
				<span>@T("Account.ForumSubscriptions")</span>
            </a>
        }
        @if (!Model.HidePrivateMessages)
        {
            <a href="@Url.RouteUrl("PrivateMessages", new { tab = "inbox" })" rel="nofollow" class="list-group-item list-group-item-action@(selItem == "privatemessages" ? " active" : "")">
                <i class="fa fa-fw fa-envelope-o list-group-item-icon"></i>
                <span>@T("PrivateMessages.Inbox")</span>
                @if (Model.UnreadMessageCount > 0)
                {
                    <span class="badge badge-pill badge-warning ml-2">@Model.UnreadMessageCount</span>
                }
            </a>
        }

        @{ Html.RenderWidget("myaccount_menu_lastitem_after"); }
    </div>
</div>

@{ Html.RenderWidget("myaccount_menu_after"); }

@{ Html.RenderAction("PollBlock", "Poll", new { systemKeyword = "MyAccountMenu" }); }

src/Presentation/SmartStore.Web/Views/Customer/Partials/_CheckUsernameAvailability.cshtml
<script type="text/javascript">
    $(function () {
    	$('#Username').closest(".input-group-btn").after(createCircularSpinner(24).attr('id', 'cua-loader').css('margin-left', '10px'));
    	$('#Username').on('input propertychange paste', function (e) {
    		$('#username-availabilty').text('');
    		$('#check-availability-button')
				.removeClass("btn-success btn-warning")
				.addClass("btn-secondary")
				.find(">i")
				.removeClass("fa-check fa-exclamation-circle")
				.addClass("fa-question-circle");
    	});
        $('#check-availability-button').on('click', function (e) {
            var btn = $('#check-availability-button');
            $('#username-availabilty').text('');
            if ($("#Username").val().length > 0) {
                $('#cua-loader').addClass("active");
                btn.attr('disabled', 'disabled');
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.Action("CheckUsernameAvailability")',
                    data: $('#Username').serialize(),
                    dataType: 'json',
                    success: function (data) {
                        btn.removeAttr('disabled');
                        btn
                            .removeClass("btn-success btn-warning btn-secondary")
                            .addClass(data.Available ? "btn-success" : "btn-warning")
                            .find(">i")
                            .removeClass("fa-check fa-question-circle fa-exclamation-circle")
                            .addClass(data.Available ? "fa-check" : "fa-exclamation-circle");

                        displayNotification(data.Text, data.Available ? "success" : "error");
                    },
                    complete: function () {
                        btn.removeAttr('disabled');
                        $('#cua-loader').removeClass("active");
                    }
                });
            } else {
                $('#username-availabilty').attr('class', 'not-available-status');
                $('#username-availabilty').text('*');
            }
            return false;
        });
    });
</script>

<span class="input-group-btn">
	<button type="button" id="check-availability-button" class="btn btn-secondary check-username-availability-button tooltip-toggle" title="@T("Account.CheckUsernameAvailability.Button")">
		<i class="fa fa-question-circle"></i>
	</button>
</span>

src/Presentation/SmartStore.Web/Views/Customer/Partials/_ExternalAuthentication.AssociateMessage.cshtml
@using SmartStore.Services.Authentication.External;

@{
    var openAuthParameters = ExternalAuthorizerHelper.RetrieveParametersFromRoundTrip(false);
}

@if (openAuthParameters != null)
{
    <div class="alert alert-warning external-auth-association">
        @T("Account.AssociatedExternalAuth.YourAccountWillBeLinkedTo") <strong class="identifier">@openAuthParameters.ExternalIdentifier</strong>
		<a href="@Url.Action("RemoveParameterAssociation", "ExternalAuthentication", new { ReturnUrl = Request.Url.ToString() })" class="remove" rel="nofollow">
			@T("Common.Remove")
		</a>            
    </div>
}